<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_lanjut_1</name>
   <tag></tag>
   <elementGuidId>0da57d5b-0f5a-4136-b4de-c1edc52798da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'event_personal_info_individual' and (text() = 'LANJUT' or . = 'LANJUT')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='event_personal_info_individual']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span > #event_personal_info_individual</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>72bde6c3-f540-42cc-a824-f57b9571b7e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>event_personal_info_individual</value>
      <webElementGuid>1e69b625-92b0-4b37-aaef-049e40383f3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LANJUT</value>
      <webElementGuid>8da588f9-9cb1-4ced-95f1-824eeca04f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;page&quot;]/div[1]/div[@class=&quot;step&quot;]/div[@class=&quot;form&quot;]/form[@class=&quot;el-form el-form--label-top&quot;]/div[@class=&quot;el-form-item el-form-item--feedback is-no-asterisk el-form-item--large&quot;]/div[@class=&quot;el-form-item__content&quot;]/div[1]/button[@id=&quot;event_personal_info_individual&quot;]/span[1]/span[@id=&quot;event_personal_info_individual&quot;]</value>
      <webElementGuid>5e25cdf8-c531-44b6-8d44-cbcfdd3bd512</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='event_personal_info_individual']</value>
      <webElementGuid>4b9ac3a9-7041-465a-a516-1e8e3ba59334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='event_personal_info_individual']/span/span</value>
      <webElementGuid>c8337b99-995e-4243-96cb-00730a5b17a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KEMBALI'])[1]/following::span[2]</value>
      <webElementGuid>cdff85e0-ebea-41cc-990e-e44ba9551c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Tinggal Sekarang / Domisili'])[1]/following::span[6]</value>
      <webElementGuid>11bd43a1-a09a-4890-861d-0ea9e6fa597c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024 PT Astra Welab Digital Arta. All rights reserved'])[1]/preceding::span[1]</value>
      <webElementGuid>e4043aed-b697-47b4-a0c6-3c37477e0bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::span[2]</value>
      <webElementGuid>7f1f6e6c-d4d7-49d1-b026-c89c7e660176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LANJUT']/parent::*</value>
      <webElementGuid>bdf1d4c1-1dc6-4389-a8ca-abcc7eb7e71f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/span</value>
      <webElementGuid>5b60e078-5d0d-45bf-bb0d-da13b9beafde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'event_personal_info_individual' and (text() = 'LANJUT' or . = 'LANJUT')]</value>
      <webElementGuid>b6a70576-290c-42f6-b309-81c108e8d5ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
