<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_jakartaBarat</name>
   <tag></tag>
   <elementGuidId>5f7da144-eca3-408f-990a-2e024625103d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Jakarta Barat' or . = 'Jakarta Barat')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#el-autocomplete-1891-item-4 > div.item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='el-autocomplete-1891-item-4']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a787bd60-23e6-4fae-bdeb-1362e1301428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item</value>
      <webElementGuid>90aeb427-00b0-4f00-92eb-4d7ee56dcca7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jakarta Barat</value>
      <webElementGuid>0a150d0c-5e71-476a-b51f-efe12aa33259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;el-autocomplete-1891-item-4&quot;)/div[@class=&quot;item&quot;]</value>
      <webElementGuid>02432c00-220e-4b0e-9459-9ad24a361c4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='el-autocomplete-1891-item-4']/div</value>
      <webElementGuid>ecbbe195-d436-40ab-aebe-29d66d57fe6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jakarta Selatan'])[1]/following::div[1]</value>
      <webElementGuid>af4fe052-2ac9-47fb-a57e-1420a471f8d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jakarta Utara'])[1]/following::div[2]</value>
      <webElementGuid>b104ec5d-fcf8-4b75-bbab-425b0c4869fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Jakarta Barat']/parent::*</value>
      <webElementGuid>dd37cfd5-c6bf-4148-b0b3-c269842e33a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div</value>
      <webElementGuid>ad7b0e63-49f3-4247-afe6-e00883ecf843</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Jakarta Barat' or . = 'Jakarta Barat')]</value>
      <webElementGuid>23d96cc0-ae38-42fd-8911-5aa132b4ad3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
