<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_lanjut</name>
   <tag></tag>
   <elementGuidId>5c1a3956-073c-4f63-ac55-7f9b7a105a0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#event_businessinfo_businessentity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='event_businessinfo_businessentity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f58fc7a4-ec05-4d14-9991-538e6683cb52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>916b427b-ac7d-4656-888f-a0b35e98a975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button el-button-big el-button--primary el-button--large</value>
      <webElementGuid>1adb030a-a110-4a18-9ac2-78a222838547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>event_businessinfo_businessentity</value>
      <webElementGuid>5bff3702-77a5-4121-b55d-246b277b63d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LANJUT</value>
      <webElementGuid>f66e3df7-f42f-4ddd-b2b6-2f74f6a86cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;page&quot;]/div[1]/div[@class=&quot;step&quot;]/div[@class=&quot;form&quot;]/form[@class=&quot;el-form el-form--label-top&quot;]/div[@class=&quot;el-form-item el-form-item--feedback is-no-asterisk el-form-item--large&quot;]/div[@class=&quot;el-form-item__content&quot;]/div[1]/button[@id=&quot;event_businessinfo_businessentity&quot;]</value>
      <webElementGuid>c56a8c28-c55f-4386-9404-9228bcf0109f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='event_businessinfo_businessentity']</value>
      <webElementGuid>b69711b2-7506-4d2e-902c-730b20c18001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[3]/div[2]/form/div[17]/div/div/button[2]</value>
      <webElementGuid>3c946482-82e9-4c91-a2df-8b5919638a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KEMBALI'])[1]/following::button[1]</value>
      <webElementGuid>4f2e6684-c102-4761-bc54-82d859b49106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/following::button[2]</value>
      <webElementGuid>9cd9909b-e343-4cde-9601-2d97e4be9fb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024 PT Astra Welab Digital Arta. All rights reserved'])[1]/preceding::button[1]</value>
      <webElementGuid>da65dd92-e86f-42c3-ad84-8f14c34a6e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>0a0d8a23-6d3f-47c3-81c1-82ee089d43c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'event_businessinfo_businessentity' and (text() = 'LANJUT' or . = 'LANJUT')]</value>
      <webElementGuid>9783929a-ff32-492f-9e42-3c258caa0189</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
