<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_camera</name>
   <tag></tag>
   <elementGuidId>86a0a733-7370-43b8-a01e-f067c8db7186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;camera&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div[3]/div[2]/form/div[4]/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c259904c-2d4a-4516-96d2-9efa29d2de9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAtUExURUdwTES17EO260W37kW37US360S47UW47US160Cv6kW37kS27UW360W27UW37RMCEMMAAAAOdFJOUwCAXtyfIO/oQBC8cDCQQceXfwAAAZlJREFUSMft1T9Lw0AUAPDrn0gjRRJ0EyQqXUsp6CBSOrhaAi0dSx2clH6GgiCICBkcXAQ/QejgIA5SHPwAbiIUm0jR2L7PYO7SJNfcS4rg2AcZkvdLcnnv7kLIIv4c8v0Bi0MtBpzDNOw+ms93fACnKHgJ8mDryQ8A2JnNXapurHJ5sOkVtTDNn0FcKCyfjs3DJwOteAA9CmoJoE1BJSY5co8xBfy1V53cPPojbABYs8DuskE1vBMiC+CNXO3CXoFse0CKAsuriK1IbFjKdRRot34n6uE9HBjK/vfsSx0MlLJhM58w0C0GL7vLIMDhKvaVQoDFNc2RETBe5ipqVETwkeFq3q+JoLTCAW0wD2yIoL3EgS7yhG9ukKCbIgi+nXWyI4JJPgQ/OaQOI8MM100W64XSDCdzCwPHQa0nxMSAbfjtrKbQCQNVb6rBCSniwNHTVBwZKcABlIm0qT4QyYwDUDbc8xy3FqMAnPetNX4jEUA0rKTFyxpEwSABlChoJgBtzhY09Daxelx+1Jtuc88qGusXi//XP8Yvh4jS6VG9mVcAAAAASUVORK5CYII=</value>
      <webElementGuid>4191185d-cc85-4fc9-87cb-5b088e4e84a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>camera</value>
      <webElementGuid>38122699-c158-4fa2-b531-0b15775b25c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>45e9f7f8-fff0-4ae4-8180-5859234c87ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>48c2105d-302d-4daf-bb5e-876815adc499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;wrapper&quot;]/div[@class=&quot;box&quot;]/div[@class=&quot;page&quot;]/div[1]/div[@class=&quot;step&quot;]/div[@class=&quot;form&quot;]/form[@class=&quot;el-form el-form--label-top&quot;]/div[@class=&quot;photo&quot;]/div[@class=&quot;el-form-item el-form-item--feedback el-form-item--large&quot;]/div[@class=&quot;el-form-item__content&quot;]/div[@class=&quot;hover el-input el-input-group el-input-group--prepend&quot;]/div[@class=&quot;el-input-group__prepend&quot;]/img[1]</value>
      <webElementGuid>7b649ba3-a175-43c6-a66e-5c1e52f69738</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[3]/div[2]/form/div[4]/div/div/div/div/img</value>
      <webElementGuid>b15e375c-ece8-4263-9db4-ea826f26481a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='camera']</value>
      <webElementGuid>1b33f225-e6c5-430f-97a3-44033fa55b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/img</value>
      <webElementGuid>ded86794-da4b-4465-b28e-0aa4daac7e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABABAMAAABYR2ztAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAtUExURUdwTES17EO260W37kW37US360S47UW47US160Cv6kW37kS27UW360W27UW37RMCEMMAAAAOdFJOUwCAXtyfIO/oQBC8cDCQQceXfwAAAZlJREFUSMft1T9Lw0AUAPDrn0gjRRJ0EyQqXUsp6CBSOrhaAi0dSx2clH6GgiCICBkcXAQ/QejgIA5SHPwAbiIUm0jR2L7PYO7SJNfcS4rg2AcZkvdLcnnv7kLIIv4c8v0Bi0MtBpzDNOw+ms93fACnKHgJ8mDryQ8A2JnNXapurHJ5sOkVtTDNn0FcKCyfjs3DJwOteAA9CmoJoE1BJSY5co8xBfy1V53cPPojbABYs8DuskE1vBMiC+CNXO3CXoFse0CKAsuriK1IbFjKdRRot34n6uE9HBjK/vfsSx0MlLJhM58w0C0GL7vLIMDhKvaVQoDFNc2RETBe5ipqVETwkeFq3q+JoLTCAW0wD2yIoL3EgS7yhG9ukKCbIgi+nXWyI4JJPgQ/OaQOI8MM100W64XSDCdzCwPHQa0nxMSAbfjtrKbQCQNVb6rBCSniwNHTVBwZKcABlIm0qT4QyYwDUDbc8xy3FqMAnPetNX4jEUA0rKTFyxpEwSABlChoJgBtzhY09Daxelx+1Jtuc88qGusXi//XP8Yvh4jS6VG9mVcAAAAASUVORK5CYII=' and @alt = 'camera']</value>
      <webElementGuid>9ff313a6-1df7-4f7b-9f06-20cf21d2703c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
