<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_lanjut</name>
   <tag></tag>
   <elementGuidId>c74396c7-e318-4bad-a7c3-367181fd5d07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'button' and @id = 'event_businessinfo_individual' and (text() = 'LANJUT' or . = 'LANJUT')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='event_businessinfo_individual']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#event_businessinfo_individual</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>33765f84-770f-4be0-8862-bd9e1a293934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>569304c2-4171-4273-8d8f-f17efd054992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>el-button el-button-big el-button--primary el-button--large</value>
      <webElementGuid>c642cb83-e9be-487e-ba93-cdd522ee6520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>event_businessinfo_individual</value>
      <webElementGuid>d8460090-008a-4d79-8934-b7548bee4686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LANJUT</value>
      <webElementGuid>164f64f4-b57d-4e3b-bcbd-bbb5e4394bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;event_businessinfo_individual&quot;)</value>
      <webElementGuid>5a71f0ed-f423-40f4-9fdd-01a3fd663436</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='event_businessinfo_individual']</value>
      <webElementGuid>7fe139d4-ef2c-4a96-9497-ba60d31f70f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[2]/div[2]/form/div[10]/div/div/button[2]</value>
      <webElementGuid>92c6cbee-eb88-4f7f-a4cd-c07ce21bb7c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KEMBALI'])[1]/following::button[1]</value>
      <webElementGuid>93964bcc-3c96-4be6-b007-910dcdda78d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kebijakan Privasi'])[1]/following::button[2]</value>
      <webElementGuid>41da1883-70a5-4eb9-a26b-3307d81256d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2024 PT Astra Welab Digital Arta. All rights reserved'])[1]/preceding::button[1]</value>
      <webElementGuid>adcd2f44-3606-4e55-810f-0c040822a2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>8b3021d7-1ccd-40ab-9e13-52301616f39e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'event_businessinfo_individual' and (text() = 'LANJUT' or . = 'LANJUT')]</value>
      <webElementGuid>5310304e-3283-4214-b0e0-375fc16d2c70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
