<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clickbox_individu3</name>
   <tag></tag>
   <elementGuidId>6ca0a9a6-9417-400c-9778-283364dca855</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/div/div[2]/div[2]/div/div[2]/div[2]/form/div[10]/div/div/label/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[1]/div/div[2]/div[2]/div/div[3]/div[2]/form/div[17]/div/div/label/span/span</value>
      <webElementGuid>60b27343-b3e4-443a-99e5-16c17e24c1ee</webElementGuid>
   </webElementProperties>
</WebElementEntity>
